name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 1. Decode keystore (binary .jks)
      - name: Decode Keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore/keystore.jks

      # 2. Create keystore.properties file
      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ github.workspace }}/keystore/keystore.jks" >> keystore/keystore.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore/keystore.properties

      # 3. Build
      - name: Build Release
        run: ./gradlew assembleRelease


      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-builds
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
          tag_name: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              
